export const GET_ALL_TODOS = "GET_ALL_TODOS";
export const GET_ALL_TODOS_SUCCESS = "GET_ALL_TODOS_SUCCESS";
export const GET_ALL_TODOS_FAIL = "GET_ALL_TODOS_FAIL";

export const CREATE_TODO = "CREATE_TODO";
export const CREATE_TODO_SUCCESS = "CREATE_TODO_SUCCESS";
export const CREATE_TODO_FAIL = "CREATE_TODO_FAIL";
